// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yeigphwgmphdxazaefuq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InllaWdwaHdnbXBoZHhhemFlZnVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4MTE5MTgsImV4cCI6MjA3MTM4NzkxOH0.jUJf2PTVCBwmAO17W_u0IEtE2tOWdstbnCzPid1doOI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});